### ISSUE TITLE
Token for deployment

### ISSUE THREAD

**Issue by dummy7554** [OpenCSGs/csghub#1378]
Hi there are two questions,
1) Can I change the whole auth system (use google sign up and redirect to my panel) ?
2) Can I upload the models on csghub-server without the token?

**Comment by HaiHui886** [comment]
#1: csghub server use casdoor as auth and please check if casdoor support. That's ok if it's yes.
#2: You have to upload model with access token.

**Comment by dummy7554** [comment]
What if casdoor doesn't support my country, I mean I can't see my country's phone code? 
Can I change auth and work it out locally (Google's auth or custom user email / password login) ? 



Also, github login was also not working locally...

**Comment by samchen8008** [comment]
May I know where you country is? We can add your country in.

**Comment by dummy7554** [comment]
Well, I live in Pakistan! 

Also this is a very crucial question, can't I independently deploy static models on platform without using access tokens and also add Custom Auth System for my SaaS?

**Comment by samchen8008** [comment]
You can but casdoor is the only option, you cannot customize it.

**Comment by hsluoyz** [comment]
@dummy7554 hi, Casdoor can support that region. Can you create a ticket at: https://github.com/casdoor/casdoor/issues ?

**Comment by dummy7554** [comment]
Sure, but tell me one thing only, if i Change the auth system and login by it, then can I upload models on the server or your specific casdoor is the only option to get the access token and upload models???

**Comment by samchen8008** [comment]
Are you talking about SaaS or On-premise?

**Comment by hsluoyz** [comment]
@dummy7554 your issue has been resolved: https://github.com/casdoor/casdoor/issues/4223#issuecomment-3369051371

**Comment by HaiHui886** [comment]
@dummy7554 You can create/get your own access token after you login, that does not depend on casdoor. 

https://opencsg.com/settings/access-token

**Comment by dummy7554** [comment]
also, my country still isnt displayed on your platform? 
So I can't access it !!

**Comment by HaiHui886** [comment]
There is an issue #1381 to tracking on this.

**Comment by hsluoyz** [comment]
@dummy7554 as answered in: https://github.com/casdoor/casdoor/issues/4223#issuecomment-3369051371, 

You can add `+92` in `Supported country codes` in organization setting

<img width="1263" height="142" alt="Image" src="https://github.com/user-attachments/assets/806aa215-7ccc-4ccb-9e18-ebf36f9de641" />
